<<<<<<< HEAD
---

version: '3.8'
=======
name: score-manager
>>>>>>> 5a6520016f86592e24c27614155e8eb66e15913a
services:
  db:
    build: ./mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: scoremanager
      MYSQL_USER: smuser
      MYSQL_PASSWORD: smpass
    volumes:
<<<<<<< HEAD
    - db-data:/var/lib/mysql
=======
    - scoremanager_db-data:/var/lib/mysql
>>>>>>> 5a6520016f86592e24c27614155e8eb66e15913a
  php:
    build: ./php
    depends_on:
    - db
    ports:
    - 80:8000
    volumes:
<<<<<<< HEAD
=======
    - ./work/public:/var/www/html
>>>>>>> 5a6520016f86592e24c27614155e8eb66e15913a
    - ./work:/work
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_sm
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
volumes:
<<<<<<< HEAD
  db-data:
=======
  scoremanager_db-data:
    external: true
>>>>>>> 5a6520016f86592e24c27614155e8eb66e15913a
